name: "API Build & Tests"

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'src/FinancialHub/*' 
      - 'src/FinancialHub/**'
  pull_request:
    branches: 
      - 'main'
      - 'release/**'
    paths:
      - 'src/FinancialHub/*' 
      - 'src/FinancialHub/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    services:
      sql-database: 
        image: mcr.microsoft.com/mssql/server:2019-latest    
        env: 
          SA_PASSWORD: "P@ssw0rd!"
          ACCEPT_EULA: "Y"
        ports: 
          - 1450:1433
              
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: './src/FinancialHub/'
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: './src/FinancialHub/'
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: './src/FinancialHub/'
