version: '3.4'
services:
  sql-database: 
    image: mcr.microsoft.com/mssql/server:2019-latest    
    tty: true
    environment: 
      - SA_PASSWORD=P@ssw0rd!
      - ACCEPT_EULA=Y
    ports: 
      - "1450:1433"
    volumes: 
      - ../database:/var/opt/mssql/data