name: Api Test Result
on:
  workflow_call:    
    inputs:
      dir:
        type: string
        required: true
      dotnet-version: 
        type: string
        default: 6.0.x

permissions:
  checks: write
  pull-requests: write

jobs:
  test_results:
    name: Code Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: 
          - auth
    env:
      project-dir: ${{ inputs.dir }}/${{ matrix.project }}

    services:
      sql-database: 
        image: mcr.microsoft.com/mssql/server:2019-latest    
        env: 
          SA_PASSWORD: "P@ssw0rd!"
          ACCEPT_EULA: "Y"
        ports: 
          - 1450:1433

    steps:
      - uses: actions/checkout@v2
            
      - name: Setup Project
        uses: ./.github/actions/build-dotnet-project
        with: 
          project-dir: ${{ inputs.dir }}
          dotnet-version: 6.0.x

      - name: Run Unit Tests
        uses: ./.github/actions/run-tests
        with: 
          project-dir: ${{ inputs.dir }}
          category: Unit
    
      - name: Run Integration Tests
        uses: ./.github/actions/run-tests
        with: 
          project-dir: ${{ inputs.dir }}
          category: Integration

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: ${{ matrix.project }} project test results
          action_fail: true
          files: "./tests/${{ matrix.project }}/**/TestResults/Results-*.xml"